### PR TITLE
Handle 404 from availability_zone_id

### LINKED ISSUE #349: availability_zone_id may return 404
### Python Version

3.8.10

### Package Version

2.7.0

### Description

In some cases `ec2_metadata.availability_zone_id` returns 404
```
----> 1 ec2_metadata.availability_zone_id
File functools.py:967, in __get__(self, instance, owner)
File ec2_metadata/__init__.py:87, in availability_zone_id(self)
File ec2_metadata/__init__.py:65, in _get_url(self, url, allow_404)
File requests/models.py:960, in raise_for_status(self)
HTTPError: 404 Client Error: Not Found for url: http://169.254.169.254/latest/meta-data/placement/availability-zone-id
```
I assume that all that is needed is to use `allow_404` in `_get_url`

### PR DESCRIPTION
**Pull request by arossert**
This will fix #349

### CODE REVIEW

**Comment by adamchainz** [comment]
Pending reply to https://github.com/adamchainz/ec2-metadata/issues/349#issuecomment-1061516561

**Comment by arossert** [comment]
@adamchainz I have replied on the issue, seems like this is only supported on instances that were created after this API was added, so there is a good reason to handle `404` in this case.

**Comment by adamchainz** [comment]
released in 2.9.1 🙌

**Comment by arossert** [comment]
Thanks a lot 👍

**Pull request merged**
