### PR TITLE
Add interface_id property to NetworkInterface to query the ENI id

### PR DESCRIPTION
**Pull request by cole14**

### CODE REVIEW

**Comment by adamchainz** [comment]
I'm not seeing this in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-categories , are you sure that it officially exists?

**Comment by cole14** [comment]
Yeah, for some reason it's not documented there but it does seem to exist. I verified it on one of my instances:

`ubuntu@instance:~$ curl http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:50:bc:a2:0f:c8/interface-id                                                                                                                      
eni-96f369b`

**Comment by cole14** [comment]
I discovered it by querying the mac document and looking at all the sub-documents that it returned:

```
ubuntu@instance:~$ curl http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:50:bc:a2:0f:c8
device-number
interface-id
local-hostname
local-ipv4s
mac
owner-id
security-group-ids
security-groups
subnet-id
subnet-ipv4-cidr-block
subnet-ipv6-cidr-blocks
vpc-id
vpc-ipv4-cidr-block
vpc-ipv4-cidr-blocks
vpc-ipv6-cidr-blocks
```

**Comment by cole14** [comment]
https://github.com/adamchainz/ec2-metadata/pull/91 has been merged in!

**Comment by adamchainz** [comment]
Thanks! Released in version 1.7.0! https://pypi.org/project/ec2-metadata/1.7.0/

**Pull request merged**
