### PR TITLE
Add instance_profile_arn and instance_profile_id

### PR DESCRIPTION
**Pull request by levisbakalinsky**

### CODE REVIEW

**Comment by levisbakalinsky** [comment]
@adamchainz, did this fail because i'm missing tests for the additional properties?

**Comment by adamchainz** [comment]
Yes, pytest-cov is saying coverage is not 100%. Plus flake8 failed:

```
Running flake8 code linting
ec2_metadata.py:139:1: E302 expected 2 blank lines, found 1
```

**Comment by levisbakalinsky** [comment]
Thanks, i've been a busy busy with other projects.

If you have any questions or concerns, please feel free to contact me
via e-mail or at the cellphone number listed below.
Kindest Regards,
Levis Bakalinsky

Cell: +1 (310) 650-7101 | Fax: +1 (323) 940-4404


On Tue, Oct 24, 2017, at 10:28 AM, Adam Johnson wrote:
> I'm going to take over and do these steps for you


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/adamchainz/ec2-metadata/pull/37#issuecomment-339068901

**Comment by adamchainz** [comment]
Released in version 1.4.0, thanks! https://pypi.python.org/pypi/ec2-metadata

**Pull request merged**
